apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: <your-root-password>
  MYSQL_DATABASE: flaskdb
  MYSQL_USER: flaskuser
  MYSQL_PASSWORD: <your-password>
